//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RemontDBEntities : DbContext
    {
        public RemontDBEntities()
            : base("name=RemontDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<FaultType> FaultTypes { get; set; }
        public virtual DbSet<Manufacturer> Manufacturers { get; set; }
        public virtual DbSet<Parameter> Parameters { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<RequestWork> RequestWorks { get; set; }
        public virtual DbSet<Spare> Spares { get; set; }
        public virtual DbSet<SpareParameter> SpareParameters { get; set; }
        public virtual DbSet<SpareType> SpareTypes { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Technic> Technics { get; set; }
        public virtual DbSet<TechnicParameter> TechnicParameters { get; set; }
        public virtual DbSet<TechnicType> TechnicTypes { get; set; }
        public virtual DbSet<Work> Works { get; set; }
    }
}
