//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.RequestWorks = new HashSet<RequestWork>();
        }
    
        public int Request_ID { get; set; }
        public int Status_ID { get; set; }
        public int FaultType_ID { get; set; }
        public int Technic_ID { get; set; }
        public int Client_ID { get; set; }
        public int Employee_ID { get; set; }
        public System.DateTime RequestDt { get; set; }
        public string SerialNumber { get; set; }
        public string Description { get; set; }
        public System.DateTime ExecutionDt { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual FaultType FaultType { get; set; }
        public virtual Status Status { get; set; }
        public virtual Technic Technic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestWork> RequestWorks { get; set; }
    }
}
