//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestWork
    {
        public int RequestWork_ID { get; set; }
        public int Request_ID { get; set; }
        public int Work_ID { get; set; }
        public int Employee_ID { get; set; }
        public Nullable<int> Spare_ID { get; set; }
        public Nullable<System.DateTime> RequestWorkDt { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Request Request { get; set; }
        public virtual Spare Spare { get; set; }
        public virtual Work Work { get; set; }
    }
}
