//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechnicParameter
    {
        public int TechnicParameter_ID { get; set; }
        public int Technic_ID { get; set; }
        public int Parameter_ID { get; set; }
        public string ParameterValue { get; set; }
    
        public virtual Parameter Parameter { get; set; }
        public virtual Technic Technic { get; set; }
    }
}
